name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and Push the Docker image to DockerHub
      run: |
        IMAGE_ID=${{ github.repository }}

        # Use Docker `latest` tag convention
        VERSION=latest

        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION

        echo "Build image"
        docker build . --file Dockerfile --tag $IMAGE_ID:$VERSION

        echo "Push image to DockerHub"
        docker push $IMAGE_ID:$VERSION

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: latest
        tags: |
          ghcr.io/${{ env.IMAGE }}:latest
          ${{ env.IMAGE }}:latest
        cache-from: type=registry,ref=ghcr.io/${{ env.IMAGE }}:latest
        cache-to: type=inline
