name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  IMAGE_NAME: go-docker-demo

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Push the Docker image to DockerHub
      run: |
        IMAGE_ID=${{ github.repository }}/$IMAGE_NAME

        # Use Docker `latest` tag convention
        VERSION=latest

        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION

        echo "Build image"
        docker build . --file Dockerfile --tag $IMAGE_ID:$VERSION

        echo "Push image to DockerHub"
        docker push $IMAGE_ID:$VERSION