name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  IMAGE_NAME: go-docker-demo

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        IMAGE_ID=${{ github.repository }}/$IMAGE_NAME

        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest

        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION

        docker build . --file Dockerfile --tag $IMAGE_ID:$VERSION

    - name: Push image
        run: docker push $IMAGE_ID:$VERSION